CREATE TABLE [prodcopy].[str_ticketopportunity]
(
[createdby] [uniqueidentifier] NULL,
[createdbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdon] [datetime] NULL,
[createdonbehalfby] [uniqueidentifier] NULL,
[createdonbehalfbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdonbehalfbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[exchangerate] [decimal] (28, 0) NULL,
[importsequencenumber] [int] NULL,
[modifiedby] [uniqueidentifier] NULL,
[modifiedbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedon] [datetime] NULL,
[modifiedonbehalfby] [uniqueidentifier] NULL,
[modifiedonbehalfbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedonbehalfbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[overriddencreatedon] [datetime] NULL,
[ownerid] [uniqueidentifier] NULL,
[owneridname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owneridtype] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owneridyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owningbusinessunit] [uniqueidentifier] NULL,
[owningteam] [uniqueidentifier] NULL,
[owninguser] [uniqueidentifier] NULL,
[statecode] [int] NULL,
[statecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[statuscode] [int] NULL,
[statuscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_accountid] [uniqueidentifier] NULL,
[str_accountidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_accountidyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_activitycount] [int] NULL,
[str_appointmentcompleted] [bit] NULL,
[str_appointmentcompletedname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_appointmentcount] [int] NULL,
[str_appointmentscheduled] [bit] NULL,
[str_appointmentscheduledname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_campaignid] [uniqueidentifier] NULL,
[str_campaignidname] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_comments] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_contactid] [uniqueidentifier] NULL,
[str_contactidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_contactidyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_daysinstage] [int] NULL,
[str_dayssincecreation] [int] NULL,
[str_description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_emailcount] [int] NULL,
[str_estimatedrevenue] [money] NULL,
[str_estimatedrevenue_base] [money] NULL,
[str_event] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_events] [int] NULL,
[str_lastactivity] [datetime] NULL,
[str_latestticketsourceid] [uniqueidentifier] NULL,
[str_latestticketsourceidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_lostreason] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_neglectmeter] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_neglectreason] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_nextactivity] [datetime] NULL,
[str_note] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_number] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_ordernumber] [int] NULL,
[str_phonecallcount] [int] NULL,
[str_pricelevelid] [uniqueidentifier] NULL,
[str_pricelevelidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_quantity] [int] NULL,
[str_revenue] [money] NULL,
[str_revenue_base] [money] NULL,
[str_stage10date] [datetime] NULL,
[str_stage10text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_stage1date] [datetime] NULL,
[str_stage1text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_stage2date] [datetime] NULL,
[str_stage2text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_stage3date] [datetime] NULL,
[str_stage3text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_stage4date] [datetime] NULL,
[str_stage4text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_stage5date] [datetime] NULL,
[str_stage5text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_stage6date] [datetime] NULL,
[str_stage6text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_stage7date] [datetime] NULL,
[str_stage7text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_stage8date] [datetime] NULL,
[str_stage8text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_stage9date] [datetime] NULL,
[str_stage9text] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_tagcount] [int] NULL,
[str_ticketopportunityid] [uniqueidentifier] NOT NULL,
[str_ticketopportunitytypeid] [uniqueidentifier] NULL,
[str_ticketopportunitytypeidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_ticketproductid] [uniqueidentifier] NULL,
[str_ticketproductidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_ticketscheduleid] [uniqueidentifier] NULL,
[str_ticketscheduleidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_ticketsourceid] [uniqueidentifier] NULL,
[str_ticketsourceidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_ticketstageid] [uniqueidentifier] NULL,
[str_ticketstageidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_wonreason] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[timezoneruleversionnumber] [int] NULL,
[transactioncurrencyid] [uniqueidentifier] NULL,
[transactioncurrencyidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[utcconversiontimezonecode] [int] NULL,
[versionnumber] [bigint] NULL,
[copyloaddate] [datetime] NOT NULL CONSTRAINT [DF_ProdCopy_str_ticketopportunity] DEFAULT (getdate()),
[str_clientestimatedclose] [datetime] NULL,
[str_clientimport] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientprobability] [int] NULL,
[str_clientreferral] [uniqueidentifier] NULL,
[str_clientreferralname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientreferralyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_contacttype] [int] NULL,
[str_contacttypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [prodcopy].[str_ticketopportunity] ADD CONSTRAINT [PK__str_tick__CDE70B1FA7CB193C] PRIMARY KEY CLUSTERED  ([str_ticketopportunityid])
GO
